[versions]
bnd = "6.4.0"
bouncycastle = "1.67"
errorprone = "2.31.0"
jacoco = "0.8.12"
junit = "4.13.2"
mockito = "2.28.2"
netty-handler = "4.1.24.Final"
netty-tcnative = "2.0.26.Final"
shadow = "7.1.2"

[plugins]
bnd = { id = "biz.aQute.bnd.builder", version.ref = "bnd" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
# Bouncycastle
bouncycastle-apis = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
bouncycastle-provider = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }

# Testing
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
jacoco-agent = { module = "org.jacoco:org.jacoco.agent", version.ref = "jacoco" }
jacoco-ant = { module = "org.jacoco:org.jacoco.ant", version.ref = "jacoco" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

# Netty
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty-handler" }
netty-tcnative = { module = "io.netty:netty-tcnative-boringssl-static", version.ref = "netty-tcnative" }
